training:
  batch_size: 8
  learning_rate: 5e-5

model:
  model_id: "qwen2.5-7b"

# data:

logging:
  log_level: "INFO"

# checkpoint:
#   save_steps: 1000
#   save_total_limit: 3
#   output_dir: "experiments"

peft:
  use_peft: false
