model:
  name: "unsloth/Qwen2.5-VL-3B-Instruct-bnb-4bit"
  load_in_4bit: true
  max_seq_length: 2048

lora:
  r: 16
  alpha: 32
  dropout: 0
  finetune_vision_layers: false
  finetune_language_layers: true
  finetune_attention_modules: true
  finetune_mlp_modules: true

data:
  train_path: "/scratch/izar/mhamelin/finebio_data/train_mini.jsonl"
  val_path: "/scratch/izar/mhamelin/finebio_data/val_mini.jsonl"

training:
  batch_size: 4                      # Lower for 3B + 8 frames
  gradient_accumulation_steps: 8     # Effective batch = 32
  warmup_steps: 10
  max_steps: 100                    # ~1 epoch on 40k samples
  learning_rate: 2.0e-4              # Standard for LoRA
  output_dir: "/scratch/izar/mhamelin/checkpoints/qwen3b_mini_test"
  save_steps: 50
  logging_steps: 10
  weight_decay: 0.01 


# Full training changes
# data:
#   train_path: "/scratch/izar/mhamelin/finebio_data/train.jsonl"
#   val_path: "/scratch/izar/mhamelin/finebio_data/val.jsonl"

# training:
#   max_steps: 1500
#   warmup_steps: 100
#   output_dir: "/scratch/izar/mhamelin/checkpoints/qwen3b_finebio_full"

