model:
  name: "Qwen/Qwen2.5-VL-3B-Instruct"
  max_seq_length: 4096
  dtype: "bfloat16"
  attn_implementation: "flash_attention_2"

lora:
  r: 32
  alpha: 64
  dropout: 0.05
  finetune_attention_modules: true
  finetune_mlp_modules: true

data:
  train_path: "/scratch/iris/finebio_processed/splits/train_10k_4_frames/finebio_train.jsonl"
  val_path: "/scratch/iris/finebio_processed/splits/train_10k_4_frames/finebio_val.jsonl"
  max_frames: 4
  # 640x640 = 409,600. Setting slightly higher to avoid accidental downsampling.
  max_pixels: 600000      # 700x700

training:
  batch_size: 16
  gradient_accumulation_steps: 1
  # Effective Batch Size = 16 * 1 * num_gpus = 16.
  
  # Optimization
  optim: "adamw_torch"
  learning_rate: 5.0e-5
  weight_decay: 0.01
  warmup_ratio: 0.1
  
  # Epoch-based training
  num_train_epochs: 3

  # A100 Specifics
  bf16: true
  fp16: false
  gradient_checkpointing: true
  
  # Checkpointing
  output_dir: "/scratch/iris/checkpoints/qwen3b_finebio_run2"
  
  save_strategy: "steps"
  save_steps: 400         # Save ~3 times per epoch (since epoch is ~1370 steps)
  save_total_limit: 2     # Keep only the last 2 checkpoints to save disk space
  
  eval_strategy: "steps"
  eval_steps: 50
  logging_steps: 5
  
  
